add homework1 ML in prod
made-ml-in-prod-2021/egorokm19 pull request #2
Opened 2021-05-05 08:44 UTC by Egorokm19

2021-05-16 13:18 UTC, malyginvlad requested changes
Проект запускается, всё хорошо, но есть небольшие недочеты по коду

2021-05-16 13:18 UTC, malyginvlad commented on ml_project/entities/train_pipeline_params.py
> +import yaml
Желательно поправить импорты библиотек

2021-05-16 13:18 UTC, malyginvlad commented on ml_project/features/build_features.py
> +
1 пробел, между импортами)

2021-05-16 13:18 UTC, malyginvlad commented on ml_project/setup.py
> +)
добавить версию python

2021-05-16 13:18 UTC, malyginvlad commented on ml_project/tests/data_generator.py
> +            dataset[col] = columns[col]
Нужен здесь цикл? Почему бы просто не написать dataset = dataset[colums] ?)

2021-05-16 13:18 UTC, malyginvlad commented on ml_project/tests/features/test_process_features.py
> +from ml_project.tests.data import data_small
поправить все импорты, привести их во всем проекте к одному виду.

2021-05-16 22:33 UTC, kinoooshnik approved these changes
В целом по коду все хорошо. Интересно с логгером сделано, что его конфигурация в отдельный конфиг вынесена. За оформление в виде пакета +.

Но есть проблемы со структурой проекта. 
Во-первых, в 95% случаев в папках с кодом должен лежать только код, а тут помимо кода в ml_project/data еще и данные, в ml_project/models метрики и модель, в ml_project/reports отчеты. Смежная история и с тестами. При тестировании чтения данных используется tmpdir - это правильно, почему бы не использовать ее и при тестировании функций модели? А то так при запуске тестов рядом с кодом появляются какие-то артефакты тестирования. 
Во-вторых, вопросы компановке. ml_project - это корень пакета, но в корне помимо setup.py лежат еще питоновские скрипты. 
В общем, я рекомендую весь код положить в отдельную директорию и чтобы там лежал только код, ноутбук и отчеты тоже отдельно, данные отдельно, артефакты обучения отдельно, конфиги отдельно. 
Еще не очень понимаю зачем тут нужен requirements.txt, если есть setup.py. 
Еще было бы круто пройтись форматтером тип black. Видно, что стараешься писать код в рамках PEP8, но следить за всеми тонкостями стандарта сложно, поэтому форматтеры и используют.
И последнее, в критериях говорилась о двух разных конфигах для обучения, а тут один для обучения, а второй для логирования. Скорее всего просто не так понятно было, поэтому ничего страшного.

Баллы

Критерии (указаны максимальные баллы, по каждому критерию ревьюер может поставить баллы частично): 
-2) Назовите ветку homework1 (1 балл) **+1**
-1) положите код в папку ml_project **+0**
0) В **описании к пулл реквесту** (а не readme) описаны основные "архитектурные" и тактические решения, которые сделаны в вашей работе. В общем, описание что именно вы сделали и для чего, чтобы вашим ревьюерам было легче понять ваш код. (2 балла) **+2**
 
1) Выполнение EDA, закоммитьте ноутбук в папку с ноутбуками (2 баллов)
Вы так же можете построить в ноутбуке прототип(если это вписывается в ваш стиль работы)
Можете использовать не ноутбук, а скрипт, который сгенерит отчет, закоммитьте и скрипт и отчет (за это + 1 балл) **+3**
 
2) Проект имеет модульную структуру(не все в одном файле =) ) (2 баллов) **+2**
 
3) использованы логгеры (2 балла) **+2**
 
4) написаны тесты на отдельные модули и на прогон всего пайплайна(3 баллов) **+3**
 
5) Для тестов генерируются синтетические данные, приближенные к реальным (3 баллов) **+3**
- можно посмотреть на библиотеки https://faker.readthedocs.io/en/, https://feature-forge.readthedocs.io/en/latest/
- можно просто руками посоздавать данных, собственноручно написанными функциями
как альтернатива, можно закоммитить файл с подмножеством трейна(это не оценивается) 
 
6) Обучение модели конфигурируется с помощью конфигов в json или yaml, закоммитьте как минимум 2 корректные конфигурации, с помощью которых можно обучить модель (разные модели, стратегии split, preprocessing) (3 балла) **+3**
 
7) Используются датаклассы для сущностей из конфига, а не голые dict (3 балла)  **+3**
 
8) Используйте кастомный трансформер(написанный своими руками) и протестируйте его(3 балла) **+3**
 
9) Обучите модель, запишите в readme как это предлагается (3 балла) **+3**
 
10) напишите функцию predict, которая примет на вход артефакт/ы от обучения, тестовую выборку(без меток) и запишет предикт, напишите в readme как это сделать (3 балла)   **+3**
 
11) Используется hydra  (https://hydra.cc/docs/intro/) (3 балла - доп баллы) **+0**
 
12) Настроен CI(прогон тестов, линтера) на основе github actions  (3 балла - доп баллы (будем проходить дальше в курсе, но если есть желание поразбираться - welcome) **+0**
13) Проведите самооценку, опишите, в какое колво баллов по вашему мнению стоит оценить вашу работу и почему (1 балл доп баллы) **+1**

Итого 1+0+2+3+2+2+3+3+3+3+3+3+3+0+0+1=32

2021-05-16 22:33 UTC, kinoooshnik commented on ml_project/reports/eda_reports.py
> +    main(EDAReportsParams)
Кажется, что так ты передаешь класс как параметр, а не объект

2021-05-16 22:33 UTC, kinoooshnik commented on ml_project/reports/reports.txt
> +5     57    1   0       140   192    0        1      148      0      0.4      1   0     1       1
Как-то тут не только первые 5 строчек датасета

2021-05-16 22:33 UTC, kinoooshnik commented on ml_project/models/utils.py
> +    }
Было бы классно, если бы тут возвращался объект dataclass, а не словарь
Хотя в случае с метриками это не так обязательно

2021-05-16 22:33 UTC, kinoooshnik commented on ml_project/train_pipeline.py
> +    with open(training_pipeline_params.metric_path, "w") as metric_file:
Сохранение метрик можно в отдельную функцию вынести

2021-05-16 22:33 UTC, kinoooshnik commented on ml_project/train_pipeline.py
> +def setup_logging(training_pipeline_params: TrainingPipelineParams):
Эту функцию лучше в файлик с функциями для логирования

2021-05-16 22:33 UTC, kinoooshnik commented on ml_project/tests/data_generator.py
> +def generate_dataframe(data_shape, random_state, columns=None):
Почему бы не сделать фикстурой в тестировании датасетов?

2021-05-16 22:33 UTC, kinoooshnik commented on ml_project/tests/models/test_metrics.py
> +import os
Кажется, что этот файлик должен называться test_pipeline

2021-05-16 22:33 UTC, kinoooshnik commented on ml_project/utils.py
> +import os
А назыавние этого файла должно говорить, что тут история про логи

2021-05-17 08:13 UTC, Egorokm19 commented on ml_project/entities/train_pipeline_params.py
> +import yaml
Исправил

2021-05-17 08:13 UTC, Egorokm19 commented on ml_project/features/build_features.py
> +
Исправил

2021-05-17 08:13 UTC, Egorokm19 commented on ml_project/setup.py
> +)
Исправил

2021-05-17 08:13 UTC, Egorokm19 commented on ml_project/tests/data_generator.py
> +            dataset[col] = columns[col]
Исправил

2021-05-17 08:13 UTC, Egorokm19 commented on ml_project/tests/features/test_process_features.py
> +from ml_project.tests.data import data_small
Исправил

2021-05-17 08:13 UTC, Egorokm19 commented on ml_project/reports/eda_reports.py
> +    main(EDAReportsParams)
Исправил)

2021-05-17 08:14 UTC, Egorokm19 commented on ml_project/reports/reports.txt
> +5     57    1   0       140   192    0        1      148      0      0.4      1   0     1       1
Исправил, забыл добавить параметр внутри head)

2021-05-17 08:14 UTC, malyginvlad approved these changes
Теперь всё хорошо))

2021-05-17 08:14 UTC, Egorokm19 commented on ml_project/models/utils.py
> +    }
Тут не стал возвращать объект dataclass и оставил словарь)

2021-05-17 08:14 UTC, Egorokm19 commented on ml_project/train_pipeline.py
> +    with open(training_pipeline_params.metric_path, "w") as metric_file:
Вынес в отдельную функцию)

2021-05-17 08:14 UTC, Egorokm19 commented on ml_project/train_pipeline.py
> +def setup_logging(training_pipeline_params: TrainingPipelineParams):
Перенес в файлик с логированием)

2021-05-17 08:15 UTC, Egorokm19 commented on ml_project/tests/data_generator.py
> +def generate_dataframe(data_shape, random_state, columns=None):
Пытался сделать с фикстурой, но не получилось)

2021-05-17 08:15 UTC, Egorokm19 commented on ml_project/tests/models/test_metrics.py
> +import os
Переименовал)

2021-05-17 08:16 UTC, Egorokm19 commented on ml_project/utils.py
> +import os
Тут оставил название прежние, так как у нас не только история логирования, но и установка логов, создание и тд)

2021-05-18 10:26 UTC, kinoooshnik commented
Структуру проекта будешь менять или так оставишь? В итоговом комментарии к ревью до баллов написал, что не так.

2021-05-18 12:08 UTC, Egorokm19 commented on ml_project/reports/eda_reports.py
> +    main(EDAReportsParams)
Исправил по описанию выше, убрал все файлы, про которые Вы писали выше в отдельную папку и изменил структуру))

2021-05-18 12:09 UTC, Egorokm19 commented
@kinoooshnik, исправил все)

2021-05-18 12:15 UTC, kinoooshnik approved these changes
Теперь со структурой все хорошо. Баллы остаются те же.

2021-05-18 12:51 UTC, merged